### ISSUE TITLE
Reduce Size

### ISSUE THREAD

**Issue by UserTaken** [offensive-security/kali-linux-docker#1]
Size matters and having ~70MB of .deb files in /var/cache/apt/archives is unnessasary. First step is to remove ~50MB of it in `kalilinux/kali`, then it is [good practice](https://docs.docker.com/articles/dockerfile_best-practices/) to have update/upgrade/install in the same layer to allow leftover removal before committing.

```
FROM kalilinux/kali
MAINTAINER muts@kali.org
ENV DEBIAN_FRONTEND noninteractive
RUN echo "deb http://http.kali.org/kali kali main contrib non-free" > /etc/apt/sources.list && \
	echo "deb-src http://http.kali.org/kali kali main contrib non-free" >> /etc/apt/sources.list && \
	echo "deb http://security.kali.org/kali-security kali/updates main contrib non-free" >> /etc/apt/sources.list && \
	echo "deb-src http://security.kali.org/kali-security kali/updates main contrib non-free" >> /etc/apt/sources.list

RUN apt-get update -y && \
	apt-get dist-upgrade -y && \
	rm -rf /var/cache/apt/archives/* /var/lib/apt/list/*

CMD ["/bin/bash"]
```

In the blog post

```
muts@macbook-air:~$ docker pull kalilinux/kali-linux-docker
muts@macbook-air:~$ docker run -t -i kalilinux/kali-linux-docker /bin/bash
root@0129d62d2319:/# apt-get install metasploit
```

was showed as an example but for reverse payloads to connect back, ports need to be ported with `-p 4444:4444` or run the network host mode with

 `docker run -it --net host kalilinux/kali-linux-docker`

Example: https://registry.hub.docker.com/u/usertaken/metasploit-framework/

**Comment by offensive-security** [comment]
Good point! Will add an "apt-get clean" at the end of the build.

**Comment by UserTaken** [comment]
@offensive-security Adding `RUN apt-get clean` at the end won't reduce the final size because each `RUN` command creates a read-only layer.

**Comment by offensive-security** [comment]
Thanks, was not aware of this. Changed to RUN apt-get -y update && apt-get -y dist-upgrade && apt-get clean

**Comment by UserTaken** [comment]
That's good but there is still ~50MB of .deb files in kalilinux/kali.

**Comment by offensive-security** [comment]
Possibly because the docker build hasn't completed yet. In any case, feel free to build upon this image and optimize it as you like!
