### ISSUE TITLE
*** lsb-release (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package base-files (--configure):

### ISSUE THREAD

**Issue by debojyotib** [offensive-security/kali-linux-docker#11]
I do get a problem when the dockerfile. I used the following docker command to build

docker build -t

I would really appreciate some help.

The error i get is the following:
-----------------------------------
Configuration file '/etc/lsb-release'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** lsb-release (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package base-files (--configure):
 EOF on stdin at conffile prompt
Errors were encountered while processing:
 base-files
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get -y update && apt-get -y dist-upgrade && apt-get clean' returned a non-zero code: 100
----------------------------------------------
The platform I am using is Ubuntu 14.04 LTS
Docker version is 
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

**Comment by steev** [comment]
I'm not entirely sure.  We pass DEBIAN_FRONTEND=noninteractive (env DEBIAN_FRONTEND noninteractive) in the Dockerfile, so it shouldn't be prompting about that file at all; that said, I looked into this and even passing -o Dpkg::Options::="--force-confdef" to the apt-get, while it got past that, there was an error with insserv.

On top of that, the images on hub are out of date by a couple months, and unfortunately, I didn't realize the name change on Hub, so I've updated both hub, and the build.sh and the Dockerfile, pointing to the correct repos and pulling from the correct hub repo.  

Sorry for the issues!
