### ISSUE TITLE
Kali debootstrap script loaded over HTTP

### ISSUE THREAD

**Issue by lucyoa** [offensive-security/kali-linux-docker#17]
Kali debootstrap script is downloaded over HTTP which seems to be a little bit dangerous:
```
curl "http://git.kali.org/gitweb/?p=packages/debootstrap.git;a=blob_plain;f=scripts/kali;h=50d7ef5b4e9e905cc6da8655416cdf3ef559911e;hb=refs/heads/kali/master" > kali-debootstrap
```
Attacker might modify the script (break the integrity) and inject malicious commands that will get executed on the victim's computer.

**Comment by steev** [comment]
This is due to the git server not running over https.  At the moment there is nothing I can do, short of git cloning the repo just to get the file.

**Comment by steev** [comment]
Now that git is served over https, we can do this, thanks for the report!
