### ISSUE TITLE
 Failed getting release file http://http.kali.org/kali/dists/kali-current/Release

### ISSUE THREAD

**Issue by Liberxue** [offensive-security/kali-linux-docker#18]
root@19c880bc4650:/# bash sh.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
debootstrap is already the newest version (1.0.90kali1).
The following package was automatically installed and is no longer required:
  libicu57
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6140    0  6140    0     0   1856      0 --:--:--  0:00:03 --:--:--  1856
I: Retrieving InRelease
I: Retrieving Release
E: Failed getting release file http://http.kali.org/kali/dists/kali-current/Release
Build failed!

**Comment by steev** [comment]
Are you still running into this issue?  kali-current hasn't been available for a while now, and I don't recall it being in our sources.list but it may have been for an older version of the docker container
