### ISSUE TITLE
WslRegisterDistribution fails with error 0x80070057

### ISSUE THREAD

**Issue by DarthSpock** [offensive-security/kali-linux-docker#24]
From Microsoft/WSL#3054
> Windows 10.0.16299.334 Pro x64 en-us (current public release build with current cumulative update KB4089848 at time of issue).
Kali Linux installed through the Store on original release date, no problem observed (but not used much).
Other distributions (Ubuntu and Debian) working fine.
Today Kali Linux got updated through the Store, to version 1.1.2.0 released on 2/22/2018.

![image](https://user-images.githubusercontent.com/33032910/37966799-83967a72-3197-11e8-8f9d-3ccb464c6076.png)

> Uninstalling and reinstalling Kali Linux package works.

I am unable to personally repro this but others have experienced this. I believe an update to the launcher is responsible. Could you go back and debug the launcher code and remedy this issue so users don't have to reinstall?

**Comment by bkr32** [comment]
+1

**Comment by ioxplo** [comment]
+1

**Comment by DarthSpock** [comment]
Still got people experiencing it.

**Comment by ioxplo** [comment]
Hi @bkr32, how do you apply the update? Thanks

**Comment by bkr32** [comment]
@DarthSpock on the WSL git there was a fix suggested by copying the kali.exe and install.tar.gz or rootfs
i did follow that and now launching the kali shortcut, it ends up using the copied rootfs rather than the appdata one

**Comment by DarthSpock** [comment]
Yes also new update, using wsl.exe will work as well if Kali is your default distro. You can configure that using wslconfig.

**Comment by DarthSpock** [comment]
Closing issue due to fix being mentioned by benhillis. Short answer, backup any relevant data to DrvFS using wsl.exe and reinstall or reset Kali app. Also for future reference, refer to https://github.com/offensive-security/Kali-WSL-chroot for Kali issues.

**Comment by ScottRFrost** [comment]
This is what I did to backup and restore my primary user home dir.

From Windows:

    wslconfig.exe /setdefault kali-rolling
    wsl.exe

Then, in WSL:

    tar cf /mnt/c/KaliHome.tar ~
    exit

Uninstall Kali in Windows store, reinstall Kali in Windows store, log on to WSL and create your user again, then in WSL:

    cd ~
    tar xf /mnt/c/KaliHome.tar
    rm /mnt/c/KaliHome.tar

**Comment by hayait599** [comment]
+1

**Comment by Salsoghyer** [comment]
This way worked for me:
1- Go to App settings of kali (go to kali in the windows programs --right click-- App settings)
2- under Reset --press on "Reset" button 
and done!
