### ISSUE TITLE
apt-get update issue after installing docker on kali linux.

### ISSUE THREAD

**Issue by dsx12** [offensive-security/kali-linux-docker#26]
I'm having this issue after installing docker; I can't run apt-get update, apt-get upgrade works fine but I'm unable to update.

my logs afters running apt-get update:

Ign:1 https://download.docker.com/linux/debian kali-rolling InRelease
Hit:2 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Err:3 https://download.docker.com/linux/debian kali-rolling Release
  404  Not Found [IP: 2600:9000:203c:4600:3:db06:4200:93a1 443]
Hit:4 https://kali.download/kali kali-rolling InRelease
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/debian kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
--
Any Ideas?

**Comment by steev** [comment]
Does docker even have a Kali-rolling repository?  I'm pretty sure if you're going to use their repository, you need to point it at buster (if they even have that) as we are based on Debian buster.  

A quick glance at the dists link at https://download.docker.com/linux/debian shows that to be the case.

I'm not sure what added that URL to your sources repository, but you will need to correct it.
