### ISSUE TITLE
Docker Experimental Features Still Required?

### ISSUE THREAD

**Issue by necrognosis** [offensive-security/kali-linux-docker#27]
I was spinning up a Kali container on a new machine, and forgot to enable experimental features. But the container still built (and seems to function) without a problem.

Are Docker's experimental features still required for getting the full use out of a Kali container?

**Comment by steev** [comment]
They may not be if —squash is now no longer marked experimental. 

Which version of docker are you running?

**Comment by necrognosis** [comment]
I'm running Docker version 18.09.3-ce

**Comment by steev** [comment]
The image builds without --squash just fine, and always has - but without --squash, the image size is larger.  We use it to reduce the size of the image when we push a new one to hub.

**Comment by necrognosis** [comment]
Ah I see, that makes sense. Sorry for wasting any time, but thanks for clarifying.

**Comment by steev** [comment]
No time wasted at all.  I was actually hoping --squash had been moved out of experimental but the docs still list it as being so :(
