### ISSUE TITLE
Where is Kali Linux tools

### ISSUE THREAD

**Issue by MiteshShah** [offensive-security/kali-linux-docker#4]
After setup Kali linux Docker image there is no tools like wpscan dnsmap.
If your docker image dont include this tools then what's the use of this docker image 

If we have to run apt-get install tollname then why we dont use directly Debian or Ubuntu docker image ?

```
root@723a04e6c655:/# wpscan
bash: wpscan: command not found
root@723a04e6c655:/# ruby
bash: ruby: command not found
root@723a04e6c655:/# cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=1.1.0
DISTRIB_CODENAME=moto
DISTRIB_DESCRIPTION="Kali GNU/Linux 1.1.0"
```

**Comment by steev** [comment]
This is a base kali image with no tools installed, so you can customize it at will.  And the reason you don't use Debian or Ubuntu docker image is that the Kali repos and Debian/Ubuntu repos don't play well together.  You can create your own docker image with whatever tools you want to install using the build script as well.
