### ISSUE TITLE
What about Kali version 2.0 ?

### ISSUE THREAD

**Issue by AlexandreHagen** [offensive-security/kali-linux-docker#6]
Hi 
Can we build a Docker image to Kali 2 ?
Thanks

**Comment by steev** [comment]
Yes - the build.sh file was pointing to the sana repositories already, and I just pushed an update to the Dockerfile itself to also point to sana.  Sorry about that!  Also, officialkali is the new org that our base image is under, not kalilinux/kali.

**Comment by AlexandreHagen** [comment]
Okey thanks !
