### ISSUE TITLE
Kali container doesn't stay running 

### ISSUE THREAD

**Issue by KINGSABRI** [offensive-security/kali-linux-docker#7]
Hi

When you run a container from an image like ***nginx*** as daemon it keeps running in the background 

```
docker run -d --name nginx nginx
```

Then check the running containers 
```
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
0f30f7324575        nginx               "nginx -g 'daemon off"   4 minutes ago       Up 4 minutes        80/tcp, 443/tcp     nginx
```
Unlike Kali image it keeps die 

- run it as daemon 
```
docker run -d --name Kali -h Kali kali_king-v1.1 
eaa06a89e05da9258b8986990cdc0f198dd07f20e3744470b703c4721c87d4a1
```

- Trying to attach to the container 
```
docker exec -it Kali bash
Error response from daemon: Container Kali is not running
```

- checking the events 
```
docker events --filter  container=Kali
2015-09-13T00:14:33.000000000+03:00 eaa06a89e05da9258b8986990cdc0f198dd07f20e3744470b703c4721c87d4a1: (from kali_king-v1.0) create

2015-09-13T00:14:33.000000000+03:00 eaa06a89e05da9258b8986990cdc0f198dd07f20e3744470b703c4721c87d4a1: (from kali_king-v1.0) start

2015-09-13T00:14:33.000000000+03:00 eaa06a89e05da9258b8986990cdc0f198dd07f20e3744470b703c4721c87d4a1: (from kali_king-v1.0) die
```

**Comment by steev** [comment]
That's because the Kali image isn't meant to be run as a daemon, whereas nginx specifically is.  You can install something like nginx on Kali and then run *that* as a daemon mode, but by default, we just run /bin/bash as the cmd so it runs, and exits.  Not really sure what you are expecting here to be honest.

**Comment by KINGSABRI** [comment]
Hi @steev , I'm expecting to run the /bin/bash as a daemon so I don't need to do 

```
docker run -d -it --name kali2 kalilinux/kali-linux-docker bash
```
Then 
```
docker exec -it kali bash
```

I believe that most ppl will use kali many times not just run it then exit and terminate the containers because mostly there are many things could be running in there (ex. handlers, beef ,etc) and wanted to available all the time.

**Comment by steev** [comment]
Unless you pass --rm it does not delete the contianer.  You connect to it once it's run via docker attach.  These images are a base.  If you want to run it in daemon mode, you need to pass something that actually *runs as a daemon*.  I'm not sure how to make that any more clear.  This is more of a topic for the forums as this is *not* a bug.
