### ISSUE TITLE
E: Package 'metasploit' has no installation candidate

### ISSUE THREAD

**Issue by a1exus** [offensive-security/kali-linux-docker#8]
I'm trying to use [Setting up a Kali Linux Docker Image](https://www.kali.org/news/official-kali-linux-docker-images/) and getting following error:

```
mbp:~ alexus$ docker pull kalilinux/kali-linux-docker
Using default tag: latest
latest: Pulling from kalilinux/kali-linux-docker

e1bfb89993bf: Pull complete 
b4be4f2256bf: Pull complete 
93d580d5b6d4: Pull complete 
7267bc58e014: Pull complete 
2c00b1e4f611: Pull complete 
a5acfcddcae4: Pull complete 
e3177c843499: Pull complete 
198c6df71ab3: Already exists 
Digest: sha256:fcc3e894b9d03b20e37f3e4748dbca798a8e1a50ec7b9ddfa1e9dbd1b208efa1
Status: Downloaded newer image for kalilinux/kali-linux-docker:latest
mbp:~ alexus$ docker run -t -i kalilinux/kali-linux-docker /bin/bash
root@dc27fae2aa3e:/# apt-get install metasploit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package metasploit is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'metasploit' has no installation candidate
root@dc27fae2aa3e:/# 
```

Please advise.

**Comment by offensive-security** [comment]
The error message says it all, there's no "metasploit package", only "metasploit-framework". Check https://www.kali.org/news/kali-linux-20-released/

**Comment by a1exus** [comment]
The error message says it all? I'm unable to see any reference to `metasploit-framework` in error message nor in `Setting up a Kali Linux Docker Image` from [Official Kali Linux Docker Images | Kali Linux](https://www.kali.org/news/official-kali-linux-docker-images/).

I've tried to run `apt-get install metasploit-framework`, however it also failed, I then ran `apt-get update && apt-get install metasploit-framework` and now it works!

Thanks!

**Comment by steev** [comment]
metasploit was removed (it's in the Kali 2.0 release notes) from Kali, we only support metasploit-framework out of the box (you can still get metasploit from R7).  That said, you should *always* apt-get update before installing any software in order to have the latest sources available.  We clean out the apt-get cache to save space thus needing to do it as well inside the docker image.

**Comment by eldada** [comment]
Please update the instructions on the https://www.kali.org/news/official-kali-linux-docker-images/ page, to avoid more issues being opened up.
I also recommend adding the `apt-get update` to the example.

**Comment by frenchi** [comment]
adding a 👍  to @eldada's comment, because I followed the steps in that guide, ran in to the same issue, then ended up here.

Is the website open source? If so, I'm happy to send a PR.

**Comment by bledwards1** [comment]
I agree. If it wasn't for this page; I would be lost. Would recommend at least adding updated instructions on the page.  Tell users to see this page for help if they get the error message reported....

**Comment by superwolfboy** [comment]
still not change on https://www.kali.org/news/official-kali-linux-docker-images/

**Comment by steev** [comment]
It's updated.

**Comment by 4k4xs4pH1r3** [comment]
apt-get install metasploit-framework -y

**Comment by steev** [comment]
That's a matter of personal preference; the command is being run once you're in the docker session.  Some people prefer -y and automatically accepting anything that gets pulled in, others prefer not to.

**Comment by GreatMen456** [comment]
apt-get install metasploit-framework -y
what -y mean?

**Comment by steev** [comment]
From running ```man apt-get```

```
       -y, --yes, --assume-yes
           Automatic yes to prompts; assume "yes" as answer to all prompts and run non-interactively. If an undesirable situation, such as changing a held package, trying to install a unauthenticated package or removing an
           essential package occurs then apt-get will abort. Configuration Item: APT::Get::Assume-Yes.
```
